name: Build docker image of applications

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/cycruise:${GITHUB_SHA}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cycruise:${GITHUB_SHA}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/cycruise:${GITHUB_SHA} ${{ secrets.DOCKERHUB_USERNAME }}/cycruise:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cycruise:latest